[project]
name = "uemath"
version = "1"
authors = [{ name = "juso" }]
description = """\
A math library with support for UEVectors and UERotators.
"""


[tool.sdkmod]
name = "uemath"
license = {name = "MIT", url = "https://choosealicense.com/licenses/mit/" }