from mods_base import Library, build_mod

from tweens.easing import (
    back_in,
    back_in_out,
    back_out,
    bounce_in,
    bounce_in_out,
    bounce_out,
    circ_in,
    circ_in_out,
    circ_out,
    cubic_in,
    cubic_in_out,
    cubic_out,
    ease,
    elastic_in,
    elastic_in_out,
    elastic_out,
    expo_in,
    expo_in_out,
    expo_out,
    linear,
    quad_in,
    quad_in_out,
    quad_out,
    quart_in,
    quart_in_out,
    quart_out,
    quint_in,
    quint_in_out,
    quint_out,
    sine_in,
    sine_in_out,
    sine_out,
)
from tweens.tween import Tween

__all__ = [
    "Tween",
    "back_in",
    "back_in_out",
    "back_out",
    "bounce_in",
    "bounce_in_out",
    "bounce_out",
    "circ_in",
    "circ_in_out",
    "circ_out",
    "cubic_in",
    "cubic_in_out",
    "cubic_out",
    "ease",
    "elastic_in",
    "elastic_in_out",
    "elastic_out",
    "expo_in",
    "expo_in_out",
    "expo_out",
    "linear",
    "quad_in",
    "quad_in_out",
    "quad_out",
    "quart_in",
    "quart_in_out",
    "quart_out",
    "quint_in",
    "quint_in_out",
    "quint_out",
    "sine_in",
    "sine_in_out",
    "sine_out",
]


mod = build_mod(cls=Library)
